export enum WindowTypes {
  LAUNCHPAD = 'LAUNCHPAD',
  GALLERY = 'GALLERY',
  SOUNDCLOUD_PLAYER = 'SOUNDCLOUD_PLAYER',
  SETTINGS = 'SETTINGS',
  ABOUT = 'ABOUT',
  NOTEPAD = 'NOTEPAD',
  TETRIS = 'TETRIS',
  STYLE_GUIDE = 'STYLE_GUIDE',
  LOGIN = 'LOGIN'
}